# Generated by Django 4.2.5 on 2023-09-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_email_contact_email_rename_name_contact_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Phone_No',
            new_name='phone',
        ),
    ]
